application: postpycon
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /css
  static_dir: static/css

- url: /admin/.*
  script: app.controller.application
  login: admin

- url: /viewed/.*
  script: app.controller.application
  login: admin

- url: /.*
  script: app.controller.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
