[tool.poetry]
name = "pycon_video_voting"
version = "0.2.0"
description = ""
authors = ["Glen Jarvis <<glen@glenjarvis.com>>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
wheel = "^0.34.2"
django = "^3.0.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
